### ISSUE TITLE
API fails to retrieve reseller date based usage stats 

### ISSUE THREAD

**Issue by shalomcarmel** [MaxCDN/python-maxcdn#15]
Hi 
I am trying to execute the reseller usage API for specific dates, and it is not working well. 
The following code is an attempt to fetch July data, but all it does is always get the current month to date. Either I am not doing something right with this API, or there is a problem with the endpoint. 

My code: 

```
#!/usr/bin/env python
import pprint as pp
from textwrap import dedent
from maxcdn   import MaxCDN
import json 


alias="globaldots"
key="this is my key"
secret="this is my secret"

from_date="2016-07-01"
to_date="2016-07-31"

# report="/monthly"
report=""
date_str="from_date=%s&to_date=%s" % (from_date, to_date)
params={"from_date":from_date, "to_date" : to_date}
maxcdn = MaxCDN(alias, key, secret)

# Get my clients 
clients = maxcdn.get("/clients.json")
i=2
clientid=clients["data"]["accounts"][i]["id"]
clientname=clients["data"]["accounts"][i]["alias"]
clientstatus=clients["data"]["accounts"][i]["status"]

stats_url="/clients/%s/reports/stats.json%s" % (clientid, report)

# Version 1: pass a dictionary of dates
client_stats=maxcdn.get(stats_url, params)
print("Version 1: pass a dictionary of dates")
print json.dumps(client_stats)
print(" ")

# Version 2: pass a query string of dates
client_stats=maxcdn.get(stats_url, params=date_str)
print("Version 2: pass a query string of dates")
print json.dumps(client_stats)
print(" ")

# Version 3: Do not pass any parameters
client_stats=maxcdn.get(stats_url)
print("Version 3: Do not pass any parameters")
print json.dumps(client_stats)
print(" ")

```

The results are identical - month to date - no matter how I pass the dates, and what type of report I run. 

Version 1: pass a dictionary of dates
{"code": 200, "data": {"total": "1", "stats": {"cache_hit": "698300293", "noncache_hit": "1899", "hit": "698302192", "size": "8331462444846"}}}

Version 2: pass a query string of dates
{"code": 200, "data": {"total": "1", "stats": {"cache_hit": "698300293", "noncache_hit": "1899", "hit": "698302192", "size": "8331462444846"}}}

Version 3: Do not pass any parameters
{"code": 200, "data": {"total": "1", "stats": {"cache_hit": "698300293", "noncache_hit": "1899", "hit": "698302192", "size": "8331462444846"}}}

**Comment by jmervine** [comment]
@shalomcarmel 

From [the docs](https://docs.maxcdn.com/), it looks like you should be using `date_from` and `date_to`, but are using `from_date` and `to_date`. Try making the change and seeing if it works correctly.

Cheers!
J

**Comment by shalomcarmel** [comment]
You are sooo right. :))
